version: '3.9'

services:

        app:
                image: appnodejs:1.0

        elbe:
                image: nginx:latest
                volumes:
                        - ./conf.d:/etc/nginx/conf.d
                depends_on:
                        - api
                ports:
                        - 3000:3000
